---
- name: Install dependencies (curl, gnupg)
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Node.js repository
  shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
  become: yes
  creates: /usr/bin/node

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes